# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.0
_src_path: gh:radio-aktywne/template-database-postgres
accountname: radio-aktywne
databasename: diamond
description: Users OIDC auth data 🪪
docs: true
docsurl: https://radio-aktywne.github.io/diamond
envprefix: DIAMOND
imagename: databases/diamond
port: 20010
registry: true
releases: true
reponame: diamond
repourl: https://github.com/radio-aktywne/diamond
